[package]
name = "generic-test"
version = "0.1.0"
authors = ["Zachary Catlin <z@zc.is>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.3.1"

[build-dependencies]
windows = "0.3.1"
